apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-echo-deployment
  labels:
    app: echo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo
  strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080