version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile2
    deploy:
      replicas: 4
    restart: always
    environment:
      PING_LISTEN_PORT: 3000
    networks:
      - my-network

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - api
    networks:
      - my-network

networks:
  my-network:
    driver: bridge